sudo: false
language: node_js
node_js: "10"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
addons:
  artifacts:
    paths:
      - $(git ls-files -i --exclude-standard --others **/__diff_output__/* | tr "\n" ":")

cache: yarn

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: yarn run codecov
