name: CI

on: [pull_request]
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    container: openstax/rex-web:CI-2020-01-26
    outputs:
      deployment-url: ${{ steps.find-deployment.outputs.url }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/cache@v2
      id: node_modules
      with:
        path: node_modules
        key: node_modules5
    - run: yarn install
    - name: Find Deployment
      id: find-deployment
      env:
        GIT_REF: ${{ github.event.pull_request.head.sha }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "::set-output name=url::$(./script/get-review-environment.bash)"

  test:
    name: Test
    runs-on: ubuntu-latest
    container: openstax/rex-web:CI-2020-01-26
    strategy:
      fail-fast: false
      matrix:
        suite: [unit, browser, build]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/cache@v2
      id: node_modules
      with:
        path: node_modules
        key: node_modules5
    - run: yarn install
    - run: yarn test:${{ matrix.suite }}
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: diff output
        path: "**/__diff_output__/*"
