name: Run Selenium

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base Url'     
        required: true
        default: 'https://staging.openstax.org'
      browser:
        description: 'Browser eg. Chrome, Firefox, MicrosoftEdge, Safari'
        default: 'Chrome'
      marker:
        description: 'Marker (optional, ignored when testrail run id is set)'
        default: 'smoke_test'
      tr_run_id:
        description: 'Testrail run ID (optional)'

jobs:
  selenium:
    runs-on: ubuntu-latest
    container: openstax/rex-web:CI

    steps:
    - uses: actions/checkout@v2

    - name: set vars
      run: |
        echo "::set-env name=BASE_URL::${{ github.event.inputs.base_url }}"
        echo "::set-env name=BROWSER::${{ github.event.inputs.browser }}"
        echo "::set-env name=MARKER::${{ github.event.inputs.marker }}"
        echo "::set-env name=TR_RUN_ID::${{ github.event.inputs.tr_run_id }}"

    - name: selenium
      env:
        TR_PROJECT_ID: ${{ secrets.testrail_project_id }}
        TR_INSTANCE: ${{ secrets.testrail_instance }}
        TR_USERNAME: ${{ secrets.testrail_username }}
        TR_PASSWORD: ${{ secrets.testrail_password }}
        SAUCELABS_USERNAME: ${{ secrets.saucelabs_username }}
        SAUCELABS_API_KEY: ${{ secrets.saucelabs_api_key }}
        SECURE_STORE_PASSWORD: ${{ secrets.secure_store_password }}
      run: |
        if [ -z "$TR_RUN_ID"]; then
          make sauce
        else
          make test-rail-sauce
        fi
